const sidebarMenuStyles = (theme) => ({
	sidebar: {
		width: "270px",
		height: "100%",
		paddingTop: "30px",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		position: "relative",
		transition: "0.4s ease-in-out",
		borderRight: `1px solid ${theme.palette.neutral.medium}`,
		[theme.breakpoints.down("sm")]: {
			display: "none",
		},
	},
	sidebarClosed: {
		width: "80px",
	},
	sidebarToggleWrap: {
		width: "25px",
		height: "25px",
		borderRadius: "50%",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		cursor: "pointer",
		right: -12,
		top: 10,
		border: `1px solid ${theme.palette.neutral.medium}`,
		backgroundColor: "white",
		color: theme.palette.neutral.main,
		position: "absolute",
	},
	logoWrap: {
		width: "100%",
		display: "flex",
		alignItems: "center",
		gap: "20px",
		marginBottom: "50px",
		paddingLeft: "30px",
		fontSize: "20px",
		fontWeight: "900",
		letterSpacing: "1.5px",
		transition: "0.4s ease-in-out",
	},
	logoWrapSmall: {
		paddingLeft: "15px",
		transition: "0.4s ease-in-out",
	},
	generalWrap: {
		width: "100%",
		display: "flex",
		flexDirection: "column",
		alignItems: "center",
		gap: "20px",
	},
	menuItem: {
		width: "100%",
		display: "flex",
		alignItems: "center",
		height: "50px",
		gap: "15px",
		paddingLeft: "50px",
		fontSize: "16px",
		fontWeight: "700",
		color: theme.palette.neutral.main,
		cursor: "pointer",
		transition: "0.4s ease-in-out",
		"&:hover": {
			transition: "0.2s ease-in-out",
			backgroundColor: `${theme.palette.primary.main}10`,
			color: theme.palette.primary.main,
		},
	},
	menuItemSmall: {
		paddingLeft: "30px",
		transition: "0.4s ease-in-out",
	},
	activeItem: {
		color: theme.palette.primary.main,
		backgroundColor: `${theme.palette.primary.main}10`,
	},
	activeIndicator: {
		backgroundColor: theme.palette.primary.main,
		position: "absolute",
		left: 0,
		width: "6px",
		height: "30px",
		borderTopRightRadius: "5px",
		borderBottomRightRadius: "5px",
	},
	mobileMenuWrap: {
		[theme.breakpoints.up("sm")]: {
			display: "none",
		},
	},
	menuBtn: {
		width: "25px",
		height: "25px",
		display: "flex",
		justifyContent: "center",
		alignItems: "center",
		cursor: "pointer",
		left: 10,
		top: 10,
		position: "absolute",
		zIndex: 100,
	},
	mobileMenu: {
		position: "absolute",
		backgroundColor: "#fff",
		top: 0,
		left: 0,
		width: "100%",
		height: "100%",
		border: "5px solid red",
	},
});

export default sidebarMenuStyles;
